#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/meetup?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: Nataku.15
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: true
#    properties:
#      hibernate:
#        hbm2ddl:
#          delimiter: ";"
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql